# Generated by Django 5.1.1 on 2025-12-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.IntegerField(blank=True, help_text='Calories per serving', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(blank=True, help_text='Cooking time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='popularity',
            field=models.IntegerField(default=0, help_text='Used for ordering popular recipes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='rating',
            field=models.FloatField(default=0, help_text='Average rating'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='rating_count',
            field=models.IntegerField(default=0, help_text='Number of ratings'),
        ),
    ]
